// Generated by gencpp from file visual_slam/ObjectLocation.msg
// DO NOT EDIT!


#ifndef VISUAL_SLAM_MESSAGE_OBJECTLOCATION_H
#define VISUAL_SLAM_MESSAGE_OBJECTLOCATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/LaserScan.h>

namespace visual_slam
{
template <class ContainerAllocator>
struct ObjectLocation_
{
  typedef ObjectLocation_<ContainerAllocator> Type;

  ObjectLocation_()
    : object_class()
    , confidence(0.0)
    , scan_data()  {
    }
  ObjectLocation_(const ContainerAllocator& _alloc)
    : object_class(_alloc)
    , confidence(0.0)
    , scan_data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_class_type;
  _object_class_type object_class;

   typedef double _confidence_type;
  _confidence_type confidence;

   typedef  ::sensor_msgs::LaserScan_<ContainerAllocator>  _scan_data_type;
  _scan_data_type scan_data;





  typedef boost::shared_ptr< ::visual_slam::ObjectLocation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visual_slam::ObjectLocation_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectLocation_

typedef ::visual_slam::ObjectLocation_<std::allocator<void> > ObjectLocation;

typedef boost::shared_ptr< ::visual_slam::ObjectLocation > ObjectLocationPtr;
typedef boost::shared_ptr< ::visual_slam::ObjectLocation const> ObjectLocationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visual_slam::ObjectLocation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visual_slam::ObjectLocation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::visual_slam::ObjectLocation_<ContainerAllocator1> & lhs, const ::visual_slam::ObjectLocation_<ContainerAllocator2> & rhs)
{
  return lhs.object_class == rhs.object_class &&
    lhs.confidence == rhs.confidence &&
    lhs.scan_data == rhs.scan_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::visual_slam::ObjectLocation_<ContainerAllocator1> & lhs, const ::visual_slam::ObjectLocation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace visual_slam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::visual_slam::ObjectLocation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visual_slam::ObjectLocation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visual_slam::ObjectLocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visual_slam::ObjectLocation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visual_slam::ObjectLocation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visual_slam::ObjectLocation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visual_slam::ObjectLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d6a12f63bbcb856ea4f2379e70ec5ab";
  }

  static const char* value(const ::visual_slam::ObjectLocation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d6a12f63bbcb856ULL;
  static const uint64_t static_value2 = 0xea4f2379e70ec5abULL;
};

template<class ContainerAllocator>
struct DataType< ::visual_slam::ObjectLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visual_slam/ObjectLocation";
  }

  static const char* value(const ::visual_slam::ObjectLocation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visual_slam::ObjectLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object_class\n"
"float64 confidence\n"
"sensor_msgs/LaserScan scan_data\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/LaserScan\n"
"# Single scan from a planar laser range-finder\n"
"#\n"
"# If you have another ranging device with different behavior (e.g. a sonar\n"
"# array), please find or create a different message, since applications\n"
"# will make fairly laser-specific assumptions about this data\n"
"\n"
"Header header            # timestamp in the header is the acquisition time of \n"
"                         # the first ray in the scan.\n"
"                         #\n"
"                         # in frame frame_id, angles are measured around \n"
"                         # the positive Z axis (counterclockwise, if Z is up)\n"
"                         # with zero angle being forward along the x axis\n"
"                         \n"
"float32 angle_min        # start angle of the scan [rad]\n"
"float32 angle_max        # end angle of the scan [rad]\n"
"float32 angle_increment  # angular distance between measurements [rad]\n"
"\n"
"float32 time_increment   # time between measurements [seconds] - if your scanner\n"
"                         # is moving, this will be used in interpolating position\n"
"                         # of 3d points\n"
"float32 scan_time        # time between scans [seconds]\n"
"\n"
"float32 range_min        # minimum range value [m]\n"
"float32 range_max        # maximum range value [m]\n"
"\n"
"float32[] ranges         # range data [m] (Note: values < range_min or > range_max should be discarded)\n"
"float32[] intensities    # intensity data [device-specific units].  If your\n"
"                         # device does not provide intensities, please leave\n"
"                         # the array empty.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::visual_slam::ObjectLocation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visual_slam::ObjectLocation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_class);
      stream.next(m.confidence);
      stream.next(m.scan_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectLocation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visual_slam::ObjectLocation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visual_slam::ObjectLocation_<ContainerAllocator>& v)
  {
    s << indent << "object_class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object_class);
    s << indent << "confidence: ";
    Printer<double>::stream(s, indent + "  ", v.confidence);
    s << indent << "scan_data: ";
    s << std::endl;
    Printer< ::sensor_msgs::LaserScan_<ContainerAllocator> >::stream(s, indent + "  ", v.scan_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISUAL_SLAM_MESSAGE_OBJECTLOCATION_H
